// @ts-nocheck
// AUTO-GENERATED. Do not edit. specta from #[tauri::command]

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startDemoJob() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_demo_job") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSaveLingqKey(key: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_save_lingq_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdLoadLingqKey() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_load_lingq_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdClearLingqKey() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_clear_lingq_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async manualSourceFromFiles(epub: string, audio: string, lang: string, title: string | null) : Promise<Result<Candidate, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("manual_source_from_files", { epub, audio, lang, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a Calibre or Libation library root and return all candidates.
 */
async cmdIngestScan(source: LibrarySource, root: string) : Promise<Result<Candidate[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_ingest_scan", { source, root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAccountProfile() : Promise<Result<AccountProfile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_account_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the caller's enrolled languages. With a username we get the
 * user-trimmed catalogue (matches the browser extension); without one we
 * fall back to the full catalogue and let the UI filter by known_words.
 */
async cmdListLanguages(username: string | null) : Promise<Result<Language[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_list_languages", { username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdListCollections(lang: string) : Promise<Result<Collection[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_list_collections", { lang }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadOneShot(candidate: Candidate, collectionId: number, lang: string) : Promise<Result<UploadResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_one_shot", { candidate, collectionId, lang }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the library. Always rebuilds from the shared `ProjectStore` and
 * rewrites `library.index.json` as a cold-start cache.
 */
async cmdLibraryList() : Promise<Result<LibraryIndex, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_library_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a Candidate as a Project. Returns `Created` with the stable
 * `ProjectId`, or `Conflict { existing, conflict_title }` if a project
 * with the derived id already exists. On conflict no write occurs — the
 * caller resolves via `cmd_create_project_with_resolution`.
 */
async cmdCreateProject(candidate: Candidate, language: string, collectionTitle: string) : Promise<Result<CreateProjectResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_create_project", { candidate, language, collectionTitle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a create-project conflict by user choice.
 * 
 * - `Replace` overwrites the existing project at the conflict id.
 * - `Skip` returns the conflict id directly without re-reading the store
 * (the conflict was already detected in `cmd_create_project`; a second
 * `store.get` would race against a delete).
 * - `NewProject` mutates the candidate's *title* and re-derives the id
 * until it lands on an unused content hash. The id is hashed from
 * `candidate.title + authors[0]`, so mutating `collection_title` alone
 * keeps the hash constant and loops forever — append `" (copy)"` to
 * `candidate.title` instead, capped at `MAX_COPY_ATTEMPTS`.
 */
async cmdCreateProjectWithResolution(candidate: Candidate, language: string, collectionTitle: string, resolution: ConflictResolution) : Promise<Result<ProjectId, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_create_project_with_resolution", { candidate, language, collectionTitle, resolution }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record the user's matcher decision and advance the project.
 */
async cmdMatcherResolve(projectId: ProjectId, condition: MismatchCondition, response: MismatchResponse, chapterCount: number, trackCount: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_matcher_resolve", { projectId, condition, response, chapterCount, trackCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a persisted project by its `join_key`.
 * 
 * The frontend reaches Match and Run routes with a stringified key in the URL
 * (e.g. `asin:B0...`, `isbn13:978...`, `uuid:...`, `ch:<hex>`). This command
 * resolves that key back to the full [`Project`] so the UI can render
 * receipts, settings, and rebuild a ProjectId for typed downstream commands
 * (notably `cmd_matcher_resolve`).
 */
async cmdProjectLoad(key: string) : Promise<Result<Project, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_project_load", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start an end-to-end project job. Returns immediately with the new job id;
 * the actual work runs on the tokio runtime and streams `JobEvent`s.
 */
async cmdStartProjectJob(projectId: ProjectId) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_start_project_job", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Signal cancellation for a previously started job. No-op if the job has
 * already finished and the token was reaped.
 */
async cmdCancelJob(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_cancel_job", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccountProfile = { username: string }
export type AppError = { kind: "Io"; message: string } | { kind: "Internal"; message: string } | { kind: "MissingApiKey" } | { kind: "Unsupported"; message: string } | { kind: "Secrets"; message: SecretError } | { kind: "Text"; message: TextError } | { kind: "Audio"; message: AudioError } | { kind: "Lingq"; message: LingqError } | { kind: "Ingest"; message: IngestError } | { kind: "Other"; message: string }
export type AudioError = { kind: "FfmpegNotFound"; message: string } | { kind: "FfmpegFailed"; message: { status: number; stderr: string } } | { kind: "Probe"; message: string } | { kind: "DurationMismatch"; message: { delta_sec: number; threshold_sec: number } } | { kind: "Io"; message: string } | { kind: "Cancelled" }
export type AudioSource = { kind: "single_file"; value: string } | { kind: "folder"; value: string } | { kind: "libation_manifest"; value: string }
export type Candidate = { source_id: string; title: string; authors: string[]; language: string | null; series: SeriesRef | null; cover_path: string | null; text_source: TextSource; audio_source: AudioSource | null; chapter_manifest: ChapterManifest | null; metadata_extras: Partial<{ [key in string]: JsonValue }> }
export type ChapterEntry = { title: string; start_sec: number; end_sec: number | null }
export type ChapterManifest = { chapters: ChapterEntry[] }
export type ChapterReceipt = { chapter_index: number; track_index?: number | null; lesson_id?: number | null; degraded?: boolean; uploaded_at?: string | null }
export type Collection = { id: number; title: string }
export type ConflictResolution = "replace" | "skip" | "new_project"
export type CreateProjectResult = { status: "created"; id: ProjectId } | { status: "conflict"; existing: ProjectId; conflict_title: string }
export type IngestError = { kind: "NotSupported" } | { kind: "Io"; message: string } | { kind: "Parse"; message: string } | { kind: "Other"; message: string }
export type JobEvent = { kind: "Started"; job_id: string; stage: Stage } | { kind: "StageChanged"; job_id: string; stage: Stage } | { kind: "Progress"; job_id: string; pct: number; message: string | null } | { kind: "Log"; job_id: string; level: LogLevel; message: string } | { kind: "ChapterDone"; job_id: string; chapter_index: number; lesson_id: number; degraded: boolean } | { kind: "Result"; job_id: string; ok: boolean; payload: JsonValue } | { kind: "Cancelled"; job_id: string } | 
/**
 * Emitted when the orchestrator can't auto-pair chapters and tracks
 * and needs the user to pick a [`MismatchResponse`]. Terminal: once
 * emitted no further events fire for this job — the UI navigates to
 * `/match`, the user resolves, and the next job kicks off fresh.
 */
{ kind: "NeedsMatch"; job_id: string; title: string; chapters: number; tracks: number; condition: MismatchCondition; options: MismatchResponse[]; preselect: MismatchResponse }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Language = { code: string; title: string; known_words: number }
export type LessonOpts = { level: string; status: string; tags: string; save: string }
export type LibraryEntry = { id: ProjectId; title: string; language: string; completed_lesson_count: number; receipt_count: number; mtime: string | null }
export type LibraryIndex = { schema_version: number; generated_at: string; entries: LibraryEntry[] }
/**
 * Bookshelf source for `cmd_ingest_scan`. Modelled as an enum so specta
 * emits a TS union and the frontend can't pass a misspelled string.
 */
export type LibrarySource = "calibre" | "libation"
export type LingqError = { kind: "Unauthorized" } | { kind: "NotFound" } | { kind: "BadRequest"; message: string } | { kind: "Server"; message: string } | { kind: "Schema"; message: string } | { kind: "Transport"; message: string } | { kind: "Io"; message: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type MatcherDecision = { condition: MismatchCondition; response: MismatchResponse; chapter_count: number; track_count: number; user_overrode?: boolean; decided_at: string }
export type MismatchCondition = "one_to_many" | "many_to_one" | "many_to_few" | "count_off" | "unalignable" | "unknown"
export type MismatchResponse = "pair_accept" | "pair_drop" | "single_lesson" | "split_proportional" | "cancel" | "unknown"
export type Project = { schema_version?: number; id: ProjectId; sources: ProjectSources; settings: ProjectSettings; receipts?: ChapterReceipt[]; queue_cursor?: number; completed_lesson_ids?: number[]; matcher_decision?: MatcherDecision | null }
/**
 * Canonical project identity (AD-021).
 * 
 * `content_hash` is the always-present fallback. Strong keys
 * (`audible_asin` / `isbn13` / `calibre_uuid`) supply higher-confidence
 * joins when available across sources.
 */
export type ProjectId = { content_hash: string; audible_asin?: string | null; isbn13?: string | null; calibre_uuid?: string | null }
export type ProjectSettings = { language: string; collection_title: string; level?: number; tags?: string[] }
export type ProjectSources = { text: TextSource; audio?: AudioSource | null; chapter_manifest?: ChapterManifest | null }
export type ProjectSummary = { id: ProjectId; title: string; language: string; receipt_count: number; completed_lesson_count: number }
/**
 * Errors raised by the secrets layer, lifted from the keyring backend.
 * 
 * Variants are intentionally coarse: the UI surfaces them as distinct
 * messages and `Backend(_)` is the catch-all so platform churn doesn't
 * break the contract.
 */
export type SecretError = { kind: "LockedKeychain" } | { kind: "UserDenied" } | { kind: "MissingEntry" } | { kind: "Backend"; message: string }
export type SeriesRef = { name: string; index: number | null }
export type Stage = { kind: "transcoding" } | { kind: "uploading" } | { kind: "parsing" }
export type TextError = { kind: "Io"; message: string }
export type TextSource = { kind: "epub"; value: string } | { kind: "loose_files"; value: { paths: string[] } } | { kind: "missing" }
export type UploadResult = { lesson_id: number; lesson_url: string }
export type WhoAmI = { ok: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
